spring:
  data:
    mongodb:
      uri: mongodb+srv://mamaan5714_db_user:iOerEzRHoX8kV7Fr@cluster0.oyadcpu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: taskdb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /task